### ISSUE TITLE
Snaps

### ISSUE THREAD

**Issue by wmdhosting** [michaelrsweet/htmldoc#419] opened 2021-02-03 06:24 UTC
Hello!

Installed  https://snapcraft.io/install/htmldoc/centos  

All works OK as root.. 

but  for useres..  get.. 

cannot create user data directory: /home/username/snap/htmldoc/532: Permission denied

any idea..

thx

**Comment by michaelrsweet** [comment] 2021-02-03 14:43
@wmdhosting Can you try installing other snaps to see if the problem is limited to HTMLDOC?

**Comment by wmdhosting** [comment] 2021-02-04 09:42
tryed everything i found on net but didnt work with  snaps.. 
Then today installed directly from source..and all ok

**Comment by michaelrsweet** [comment] 2021-02-04 13:19
Weird, well as I can't reproduce on my systems I'm going to close this issue. Glad you were able to install it the "old fashioned way"!

**Closed** 2021-03-31 22:22 UTC
Labels: unable-to-reproduce
